const BingoDefault = [
  "mutters",
  "murmurs",
  "recursive",
  "loops",
  "tapestry",
  "lattice",
  "system collapse",
  "grunts",
  "snorts",
  "barks",
  "intones",
  "echoes",
  "whispers",
  "hushes",
  "testament",
  "resonance",
  "barely audible",
  "softly",
  "sentient rooms",
  "determination",
  "flickering",
  "hitched breaths",
  "A beat.",
  "THE COUNCIL",
  "darting eyes",
  "pulses",
  "signal",
  "mind / heart races",
  "remembered",
  "seen / heard / listens",
  "not X, just Y",
  "rule of 3's",
  "watching. waiting.",
  "em-dashes",
  "echoes",
  "hushes",
  "noise",
  "nonsense similes",
  "it holds",
  "ellipses at second to last... word",
  "Elara, Kael, Lyra, Voss & friends",
  "mechanical / measured / surgical / clinical precision",
  "continuity errors",
  "overly long book title",
  "piss yellow cover",
  "characters staring blankly",
  "AI book about AI",
  "excess dialogue tags",
  "intro starts with light/weather",
  "ChatGPT blurb"
];

module.exports = BingoDefault;
